### ISSUE TITLE
Change exported time target to prevent event sample not enough

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry-holding/performance-summary-collection#9]
Change exported time target from Random-Float-Device to Random-UnsignedInteger-Device.
https://github.com/edgexfoundry-holding/performance-summary-collection/blob/master/lib/EventExportedTime.py#L68

**Comment by cloudxxx8** [comment]
We made this change due to the frequency of Random-Float-Device is too long to test the exported time
